services:
  flashsnap:
    build:
      context: .
      args:
        VITE_UMAMI_WEBSITE_ID: ${VITE_UMAMI_WEBSITE_ID}
    container_name: flashsnap
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
